[package]
name = "raytracer"
version = "0.1.0"
authors = ["Nathaniel Shead <natattak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.4"
rand = "0.7"
indicatif = "0.15"
